require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
Rails: { Enabled: true }

Metrics/BlockLength: { Exclude: [db/schema.rb, spec/**/*_spec.rb] }
Rails/HasManyOrHasOneDependent: { Enabled: false }
Style/Documentation: { Enabled: false }
