# https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md

require: rubocop-rspec

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
Rails: { Enabled: true }

Metrics/BlockLength: { Exclude: [config/**/*.rb, spec/**/*_spec.rb] }
RSpec/DescribeClass: { Exclude: [spec/db/**/*] }
RSpec/ExampleLength: { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }
Rails/HasManyOrHasOneDependent: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/MixinUsage: { Exclude: [bin/**] }
Style/SafeNavigation: { Enabled: false }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/SymbolArray: { EnforcedStyle: brackets }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/WordArray: { EnforcedStyle: brackets }
Style/GuardClause: { MinBodyLength: 3 }

# Things that can be improved
Metrics/AbcSize:
  Exclude:
    - app/poros/google_place_params_parser.rb
    - app/controllers/listings_controller.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**
    - app/poros/google_place_params_parser.rb
    - app/controllers/listings_controller.rb

Metrics/ClassLength:
  Exclude:
    - app/controllers/listings_controller.rb

Metrics/LineLength:
  Exclude:
    - app/controllers/application_controller.rb
    - app/controllers/listings_controller.rb
    - db/migrate/**

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/listings_controller.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/listings_controller.rb
