# https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md

require: rubocop-rspec

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
Rails: { Enabled: true }

Metrics/MethodLength: { Exclude: [db/migrate/**] }
RSpec/MultipleExpectations: { Enabled: false }
Rails/HasManyOrHasOneDependent: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/MixinUsage: { Exclude: [bin/**] }
Style/SafeNavigation: { Enabled: false }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/SymbolArray: { EnforcedStyle: brackets }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/WordArray: { EnforcedStyle: brackets }

# Things I'm not prepared to deal with at the moment. Feel free to refactor.
Metrics/AbcSize:
  Exclude:
    - '**/app/models/listing.rb'
    - '**/app/controllers/listings_controller.rb'
    - app/poros/google_place_params_parser.rb

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - app/poros/google_place_params_parser.rb

Metrics/ClassLength:
  Exclude:
    - '**/controllers/listings_controller.rb'

Metrics/BlockLength:
  Exclude:
    - '**/environments/production.rb'
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Exclude:
    - '**/spec/controllers/listings_controller_spec.rb'
