require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
Rails: { Enabled: true }

Metrics/BlockLength: { Exclude: [spec/**/*_spec.rb] }
Rails/HasManyOrHasOneDependent: { Enabled: false }
Style/Documentation: { Enabled: false }
