# https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md

require: rubocop-rspec

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
Rails: { Enabled: true }

Metrics/BlockLength: { Exclude: [spec/**/*_spec.rb] }
Metrics/MethodLength: { Exclude: [db/migrate/**] }
Rails/HasManyOrHasOneDependent: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/MixinUsage: { Exclude: [bin/**] }
Style/SafeNavigation: { Enabled: false }

# Things I'm not prepared to deal with at the moment. Feel free to refactor.
Metrics/AbcSize:
  Exclude:
    - '**/listings_controller.rb'
